### ISSUE TITLE
Apuri ei toimi aisin muutoksen jälkeen

### ISSUE THREAD

**Issue by MasseR** [korsumaki/lentosuunnitelma-apuri#6]
Lentosuunnitelman osoite on muuttunut ja lentosuunnitelma-apuri antaa nyt 404.

**Comment by korsumaki** [comment]
Niinpä näyttää. Kiitos tiedosta, täytyy tutkia.

**Comment by korsumaki** [comment]
Nyt korjattu vaihtamalla HTTP GET metodi POST metodiksi, ja päivittämällä uusi lomakkeen osoite.
